### ISSUE TITLE
Crash when trying to change video codec

### ISSUE THREAD

**Issue by dd5f** [AronParker/AviRecorder#1]
.NET Framework 4.6.2 is installed.

**Comment by AronParker** [comment]
I'm looking into it atm. I'd encourage you to try the 32 bit version of the program *(AviRecorder_x86.exe)* which I uploaded in [releases](https://github.com/AronParker/AviRecorder/releases) . On the machines that were affected by this issue, 32 bit was working fine.

Please check whether 32 bit works out for you. This is just a temporary workaround, I'll try to fix it asap.

**Comment by dd5f** [comment]
32 bit seems to is working for me. Haven't encountered any other issues aswell.

**Comment by AronParker** [comment]
Fixed a crash on the "logitech i420 codec" on 64 bit versions. The new version of available here: [Releases](https://github.com/AronParker/AviRecorder/releases). Please reopen this if the issue still presists.
