### ISSUE TITLE
Can't find executable

### ISSUE THREAD

**Issue by Shpee64** [AronParker/AviRecorder#2]
This is probably a pretty stupid question but after downloading the zip folder and unzipping it I can't find the file I'm supposed to doubleclick to open the program in the "AviRecorder-master" folder or any subfolders.

**Comment by AronParker** [comment]
Hey you can find the binaries of the program here: [Releases](https://github.com/AronParker/AviRecorder/releases). You can find this page under the code tab, above the green bar.
