### ISSUE TITLE
Suggestion: Tooltips

### ISSUE THREAD

**Issue by Freerider3434** [AronParker/AviRecorder#3]
I read through your documentation of tools and figured, it'd be great if it displayed, when using your program via **tooltips** e.g.

![ic510746](https://cloud.githubusercontent.com/assets/26279087/23708127/28fab7d2-0415-11e7-9b45-282498db1689.png)

What do you think?

**Comment by AronParker** [comment]
Thanks for the suggestion! I'll try to implement this for the next update.

**Comment by Freerider3434** [comment]
Wow, thanks for the fast reply!

**Comment by AronParker** [comment]
Sure thing! Implemented it, It'll be live the next version. Thanks again for the suggestion!
